title: Data Analisys For AdventureWorksDW2022
logo: assets/images/Logo Github Photo.png
#descrition:
#sho_download: true
menu:
  - title: "FactResellersSales table"
    url: "https://github.com/AldoReyes84/Data-Analisys_For-AdventureWorksDW2022_SQL_PowerBI_Python_Excel/tree/main#factresellerssales-table"
  - title: "FactInternetSales table"
    url: "## FactInternetSales table"
  - title: "FactFinance table"
    url: "##FactFinance table"
  

