Title: Aldo Reyes
logo: Assets/Images/logo_github_photo.png
#descrition:
#sho_download: true


nav:
  - Inicio: index.md
  - Análisis:
      - Resellers: resellers.md
      - Internet Sales: internet_sales.md
  - Hoja de Balance: balance_sheet.md
  - GitHub: https://github.com/aldoan84/main




theme: jekyll-theme-minimal
