title: Aldo Reyes
logo: Assets/Images/logo_github_photo.png
#descrition:
#sho_download: true


menu:
  - title: Profile
    url: https://aldoreyes84.github.io/AldoReyes.github.io/
  - title: Projects
    url: /about/
  - title: Data Analysis
    url: https://aldoreyes84.github.io/Data-Analisys_For-AdventureWorksDW2022_SQL_PowerBI_Python_Excel/
  - title: SQL Server
    url: https://aldoreyes84.github.io/SQL_Server_AdventureWorks/


layout: default
#theme: jekyll-theme-minimal
