Title: Aldo Reyes
logo: ASSETS/images/Logo Github Photo.png
#descrition:
#sho_download: true
menu:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"

theme: jekyll-theme-minimal
