title: Data Analisys For AdventureWorksDW2022
logo: assets/images/Logo Github Photo.png
#descrition:
#sho_download: true
menu:
  - title: "FactResellersSales table"
    url: "## FactResellersSales table"
  - title: "FactInternetSales table"
    url: "## FactInternetSales table"
  - title: "FactFinance table"
    url: "##FactFinance table"
  

