Title: Aldo Reyes
logo: ASSETS/images/Logo Github Photo.png
#descrition:
#sho_download: true
documentation_url: "https://github.com/AldoReyes84/Data_Analisys_For_AdventureWorksDW2022"

theme: jekyll-theme-minimal
